// READONLY

export const AUTH_SIGNIN = 'AUTH_SIGNIN'; 
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_UPDATE_STATUS = 'AUTH_UPDATE_STATUS';